config/routes.rb
Rails.application.routes.draw do


  resources :friendships
  resources :profiles
  get 'follows/create'
  get 'follows/destroy'
  get 'user/create'
  get 'chanel/index'
  get 'perfil/index'
  get 'about/index'


  resources :channels
  resources :areas
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :user do
    member do
      get :followers
    end
  end
  get 'welcome/index'
  get 'users/:id' => 'users#show'
 resources :posts do
      member do
      put "like", to: "posts#upvote"
      put "unlike", to: "posts#downvote"
    end
  end
  
mount Commontator::Engine => '/commontator'

devise_scope :user do
  authenticated :user do
    root 'welcome#index', as: :authenticated_root
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

match :follow, to: 'follows#create', as: :follow, via: :post
match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
	#has_and_belongs_to_many :users  #Crea una entidad intermedia en la base de datos llamada AreaUser
	#has_and_belongs_to_many :channels #Crea una entidad intermedia en la base de datos llamada AreaChannel
  has_many :knowledges
  has_many :users, through: :knowledges
  has_many :timelines
  has_many :channels, through: :timelines
end

app/models/channel.rb
class Channel < ApplicationRecord
  #has_and_belongs_to_many :areas #Crea una entidad intermedia en la base de datos llamada AreaChannel
  belongs_to :user
  has_many :posts
  has_many :timelines
  has_many :areas, through: :timelines
  mount_uploader :image, ImageUploader

  def self.search(search)
    where("nombre LIKE ?", "%#{search}%")
    where("descripcion LIKE ?", "%#{search}%")
  end
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

  validates_presence_of :follower
  validates_presence_of :followable
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/knowledge.rb
class Knowledge < ApplicationRecord
  belongs_to :area
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  acts_as_commontable
  has_many :comments
  belongs_to :user
  belongs_to :channel

  validates :contenido, :presence => true, :if => :imagenvacia?

  def imagenvacia?
    image.nil?
  end
  mount_uploader :image, ImageUploader

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  belongs_to :area
  belongs_to :channel
end

app/models/user.rb
require "httparty"
require "json"

class User < ApplicationRecord
  has_many :comments
  has_many :posts, dependent: :destroy
  has_many :channels
  has_many :knowledges
  has_one :profile
  has_many :areas, through: :knowledges
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :anti_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :anti_friends, :through => :anti_friendships, :source => :user
  acts_as_commontator
  acts_as_followable
  acts_as_follower
  validates :cedula, :presence => true
  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include HTTParty
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   def self.validacion

      @json = get("http://localhost:4040/graduates.json")
      @json = @json.to_json
      @parsed_json = ActiveSupport::JSON.decode(@json)
      @no = @parsed_json

      return @no

    end

    def self.search(search)
      where("nombre LIKE ?", "%#{search}%")
      where("apellido LIKE ?", "%#{search}%")
    end

end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index

    @channels = Channel.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 8)

    if params[:search]
      @channels = Channel.search(params[:search]).order("created_at DESC")
    else
      @channels = Channel.all.order('created_at DESC')
    end

  end

  # GET /channels/1
  # GET /channels/1.json
  def show

    @post = Post.new
    # @posts = Post.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 7)
    @posts = Post.all.where(:channel_id => @channel.id).order('created_at DESC').paginate(:page => params[:page], :per_page => 10)

  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = current_user.channels.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:nombre, :descripcion, :user_id, :image, area_ids:[])
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/chanel_helper.rb
module ChanelHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/perfil_helper.rb
module PerfilHelper
  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/user_helper.rb
module UserHelper
  def is_current_user?(user)
    user == current_user
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/channels/_channel.html.erb
<div class="col-xs-12 col-sm-5 pull-right">
    <div class="thumbnail">
        <% if channel.image.channel_pic.url.present?%>
        <%= link_to channel do%>
        <%=  image_tag(channel.image.channel_pic.url, class: 'img-responsive') %>
        <% end %>
        <% end %>
        <div class="caption">
            <h1 class="canaltitle">
                <center><%= link_to channel.nombre, channel %></center>
            </h1>
            <hr>
            <p style="font-size: 1.5em"><strong><%= channel.descripcion %></strong></p>
            <h6>Creado por:
                <strong>

                    <%= channel.user.nombre %>
                    <%= channel.user.apellido%></strong>
                    <%=  image_tag(channel.user.image.thumby.url, class: 'img-circle', style: 'margin-left:4px; margin-top:-5px;' ) %>
            </h6>
            <hr>
            <p><%= link_to "Visitar Canal", channel, class: "btn btn-danger" %>
            </p>
        </div>
    </div>
</div>

app/views/channels/_form.html.erb
<div class="col-xs-12 col-sm-6 col-md-4 col-sm-offset-3 col-md-offset-4">
    <div class="panel panel-default devise-bs">
        <div class="panel-heading">
            <h4>Información del canal</h4>
        </div>
        <div class="panel-body">
            <%= form_for(channel) do |f| %>
            <% if channel.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(channel.errors.count, "error") %>
                    prohibited this channel from being saved:</h2>

                <ul>
                    <% channel.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
            <% end %>

            <div class="form-group">
                <%= f.label :nombre %>
                <%= f.text_field :nombre, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= f.label :descripcion %>
                <%= f.text_area :descripcion,  class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= f.label :imagen_de_cabecera %>
                <%= f.file_field :image %>
            </div>

            <label for="select" class=" control-label">Areas de Conocimiento</label>
            <div class="form-group form-control" style="height: 120px; overflow-y: scroll;">

                <%= f.collection_check_boxes :area_ids, current_user.areas.all, :id, :nombre do |b| %>
                <div class="collection-check-box">
                    <%= b.check_box %>
                    <%= b.label %>
                </div>
                <% end %>

            </div>

            <div class="actions">
                <%= f.submit t('.crear', default: ' Guardar'), class: 'btn btn-success btn-block' %>

            </div>
            <% end %>
        </div>
    </div>
</div>
</div>

app/views/channels/edit.html.erb
<center> <h1>Edita el canal</h1></center> 

<%= render 'form', channel: @channel %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<p id="notice"><%= notice %></p>
<div >
    <%= render @channels %>
</div>

app/views/channels/new.html.erb
<%= render 'form', channel: @channel %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<div class="col-xs-12 col-sm-8 col-md-6 col-md-offset-3 ">
    <center>
        <h1 style="font-size: 4.5em" ><%=@channel.nombre%></h1>
      <strong><p class="text-muted"><%= @channel.descripcion%></p></strong>
    </center>

    <br>

    <div class="panel panel-default" id="posts">

        <div class="panel-body">
            <%= form_for(@post, remote: true) do |f| %>

            <span>
                <h1 class="panel-title pull-left" style="font-size:30px;">
                    <%= current_user.nombre %>
                    <small><%= current_user.apellido %></small>
                    <i class="fa fa-check text-success" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="<%= current_user.nombre %> is sharing with you"></i>
                </h1>
                <div class="dropdown pull-right" type="button" id="dropdownMenu1" aria-haspopup="true" aria-expanded="true">

                    <%= f.submit t('.publicar', default: 'Publicar'), class: 'btn btn-success' %>
                </div>

            </span>
            <br>
            <br><br>
            <div class="media-body">
                <div class="form-group">
                    <%= f.text_area :contenido, class: 'form-control post_content',  rows: '4', placeholder: 'Comparte tus conocimientos...'  %>
                    <%= f.hidden_field :channel_id , :value => @channel.id %>
                </div>
            </div>
            <span class="pull-left btn btn-xs btn-warning btn-file glyphicon glyphicon-picture">

                <%= f.file_field :image %>

            </span>
            <% end %>
        </div>

    </div>

        <div id="container_posts">
    <% @posts.each do |post|%>

    <div class="panel panel-default" id="post_<%= post.id %>">

        <div class="panel-body">
            <div class="pull-left">
                <a href="#">
                    <% if current_user.image.thumby.url.present?%>
                    <%=  image_tag(current_user.image.thumb.url, class: 'img-circle', style: 'margin-right:8px; margin-top:-5px;' ) %>
                    <% end %>

                </a>
            </div>
            <h4><%= link_to post.user.nombre, controller: "users", action: "show", id: post.user.id %>

                <small>
                    <small>
                        <a href="#" style="text-decoration:none; color:grey;">
                            <i>
                                <i class="fa fa-clock-o" aria-hidden="true"></i>
                                <%= time_ago_in_words(post.created_at) %></i>
                        </a>
                    </small>
                </small>
            </h4>
            <span>
                <div class="navbar-right">
                    <% if current_user.id == post.user.id %>
                    <div class="dropdown">
                        <button class="btn btn-link btn-xs dropdown-toggle" type="button" id="dd1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            <i class="fa fa-angle-down" aria-hidden="true"></i>

                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dd1" style="float: right;">
                            <li type="button" data-toggle="modal" data-target="#myupdatepost_<%= post.id%>">
                                <i class="fa fa-pencil" style="margin-left:25px"></i>
                                <span style="margin-left:5px">Editar</span>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                                <%= link_to post, method: :delete, remote: true, data: { confirm: '¿Estás seguro que deseas eliminar esta publicación?' } do %>
                                <%= fa_icon "trash", text: "Eliminar" %>
                                <% end %>
                            </li>
                        </ul>
                    </div>
                    <% end %>
                </div>
            </span>
            <hr>
            <div class="post-content">

                <% if post.image.present? %>
                <div class="attachment">
                    <center><%= image_tag(post.image.post_img.url, class: 'img-responsive') %></center>
                </div>
                <% end %>
                <br>
                <p>
                    <%= post.contenido %></p>

            </div>
            <hr>
            <div>
                <div class="pull-right btn-group-xs">

                    <%= link_to like_post_path(post.id), method: :put, remote: true, class: "btn btn-default" do %>
                    <span class="glyphicon glyphicon-heart"></span>
                    <%= post.get_upvotes.size %>
                    <% end %>

                    <span class="pull-right" style="margin-left: 8px;">
                        <%= social_share_button_tag(@post.id,'data-twitter-title' => 'Chequea mi publicación en Campus:') %>
                    </span>
                </div>

                <br>
            </div>
            <hr>
            <div class="media">
                <div class="pull-left">

                    <a href="#">
                        <% if current_user.image.thumby.url.present?%>
                        <%=  image_tag(current_user.image.thumby.url, class: 'img-circle', style: 'margin-right:-5px; margin-left:3px; margin-top:6px' ) %>
                        <% end %>
                    </a>
                </div>

                <div class="media-body">
                <%= commontator_thread(post)%>

                </div>
            </div>
        </div>

    </div>

    <!--- MODAL -->

    <!-- Modal -->
    <%= form_for(post, :method => :put, remote: true) do |f| %>
    <div class="modal fade" id="myupdatepost_<%= post.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Editar publicación</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <%= f.text_area :contenido, class: 'form-control' %>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="myupdatebutton_<%= post.id %>" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
                    <%= submit_tag "Guardar Cambios", class: "btn btn-success" %>
                </div>
            </div>
        </div>
    </div>
    <% end %>

    <% end %>

    </div>
    <center>
        <%= will_paginate @posts, renderer: BootstrapPagination::Rails, previous_label: "Nuevos", next_label: "Viejos", inner_window: 1, outer_window: 0 %>
    </center>
</div>

<% if current_user.id == @channel.user.id %>
<%= link_to edit_channel_path(@channel), class: "btn btn-success btn-xs" do%>
<%= fa_icon "pencil", text: "Editar Canal" %>
<% end %>
<% end %>