config/routes.rb
Rails.application.routes.draw do


  resources :friendships
  resources :profiles
  get 'follows/create'
  get 'follows/destroy'
  get 'user/create'
  get 'chanel/index'
  get 'perfil/index'
  get 'about/index'


  resources :channels
  resources :areas
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :user do
    member do
      get :followers
    end
  end
  get 'welcome/index'
  get 'users/:id' => 'users#show'
 resources :posts do
      member do
      put "like", to: "posts#upvote"
      put "unlike", to: "posts#downvote"
    end
  end
  
mount Commontator::Engine => '/commontator'

devise_scope :user do
  authenticated :user do
    root 'welcome#index', as: :authenticated_root
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

match :follow, to: 'follows#create', as: :follow, via: :post
match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/area.rb
class Area < ApplicationRecord
	#has_and_belongs_to_many :users  #Crea una entidad intermedia en la base de datos llamada AreaUser
	#has_and_belongs_to_many :channels #Crea una entidad intermedia en la base de datos llamada AreaChannel
  has_many :knowledges
  has_many :users, through: :knowledges
  has_many :timelines
  has_many :channels, through: :timelines
end

app/models/channel.rb
class Channel < ApplicationRecord
  #has_and_belongs_to_many :areas #Crea una entidad intermedia en la base de datos llamada AreaChannel
  belongs_to :user
  has_many :posts
  has_many :timelines
  has_many :areas, through: :timelines
  mount_uploader :image, ImageUploader

  def self.search(search)
    where("nombre LIKE ?", "%#{search}%")
    where("descripcion LIKE ?", "%#{search}%")
  end
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

  validates_presence_of :follower
  validates_presence_of :followable
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/knowledge.rb
class Knowledge < ApplicationRecord
  belongs_to :area
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  acts_as_commontable
  has_many :comments
  belongs_to :user
  belongs_to :channel

  validates :contenido, :presence => true, :if => :imagenvacia?

  def imagenvacia?
    image.nil?
  end
  mount_uploader :image, ImageUploader

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  belongs_to :area
  belongs_to :channel
end

app/models/user.rb
require "httparty"
require "json"

class User < ApplicationRecord
  has_many :comments
  has_many :posts, dependent: :destroy
  has_many :channels
  has_many :knowledges
  has_one :profile
  has_many :areas, through: :knowledges
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :anti_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :anti_friends, :through => :anti_friendships, :source => :user
  acts_as_commontator
  acts_as_followable
  acts_as_follower
  validates :cedula, :presence => true
  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include HTTParty
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   def self.validacion

      @json = get("http://localhost:4040/graduates.json")
      @json = @json.to_json
      @parsed_json = ActiveSupport::JSON.decode(@json)
      @no = @parsed_json

      return @no

    end

    def self.search(search)
      where("nombre LIKE ?", "%#{search}%")
      where("apellido LIKE ?", "%#{search}%")
    end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/chanel_helper.rb
module ChanelHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/perfil_helper.rb
module PerfilHelper
  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/user_helper.rb
module UserHelper
  def is_current_user?(user)
    user == current_user
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/commontator/comments/_actions.html.erb
<% # Clients of this partial must supply the following variables:
   # comment
   # user
%>

<% can_edit = comment.can_be_edited_by?(user)
   can_delete = comment.can_be_deleted_by?(user) %>

<% if can_edit %>
  <%= link_to t('commontator.comment.actions.edit'),
              commontator.edit_comment_path(comment),
              :id => "comment_#{comment.id.to_s}_edit_link",
              :class => "comment_edit_link",
              :remote => true %>
<% end %>

&nbsp;

<% if can_delete %>
  <% is_deleted = comment.is_deleted? %>
  <% del_string = is_deleted ? 'undelete' : 'delete' %>
  <%= link_to t("commontator.comment.actions.#{del_string}"),
              commontator.polymorphic_path([del_string, comment]),
              :confirm => (!is_deleted ? t('commontator.comment.actions.confirm_delete') : nil),
              :method => :put,
              :id => "comment_#{comment.id.to_s}_#{del_string}_link",
              :class => "comment_#{del_string}_link",
              :remote => true %>
<% end %>

app/views/commontator/comments/_body.html.erb
<% # Clients of this partial must provide the following variable:
   # comment
%>

<%= simple_format comment.is_deleted? ? \
      t('commontator.comment.status.deleted_by',
        :deleter_name => Commontator.commontator_name(comment.editor)) : \
      comment.body %>

app/views/commontator/comments/_form.html.erb
<% # Clients of this partial must provide the following variables:
   # comment
   #
   # Optionally, they can also supply the following variables:
   per_page ||= nil
   thread ||= nil
   no_remote ||= false
%>

<% config = comment.thread.config %>

<% if comment.errors.any? %>
  <div class="comment_error_explanation">
    <h3><%= t "commontator.comment.errors.#{comment.id.blank? ? 'create' : 'update'}" %></h3>

    <ul>
      <% comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for([commontator, thread, comment],
             :remote => !no_remote) do |f| %>

  <%= hidden_field_tag :per_page, per_page %>

  <div class="comment_form_field">
    <%= f.text_area :body, :rows => '3', class: 'form-control' %>
    <%= javascript_tag('Commontator.initMentions()') if Commontator.mentions_enabled %>
  </div>

  <div class="comment_form_actions">
    <%= f.submit t("commontator.comment.actions.#{comment.id.blank? ? 'create' : 'update'}"), class: 'btn btn-success btn-xs' %>
    <%= f.submit t('commontator.comment.actions.cancel'), :name => 'cancel', class: 'btn btn-warning btn-xs' %>
  </div>

<% end %>

app/views/commontator/comments/_list.html.erb
<% # Clients of this partial must supply the following variables:
   # comments
   # user
%>

<% comments.includes(:creator, :editor).each do |comment| %>
  <%= render :partial => 'commontator/comments/show',
             :locals => { :comment => comment,
                          :user => user } %>
<% end %>

app/views/commontator/comments/_show.html.erb
<% # Clients of this partial must supply the following variables:
   # comment
   # user
%>

<% creator = comment.creator
   name = Commontator.commontator_name(creator) || ''
   link = Commontator.commontator_link(creator, main_app) || ''
   avatar = Commontator.commontator_avatar(creator, self) || ''
%>

<div id="comment_<%= comment.id.to_s %>_div" class="panel-body">
  <hr>  
  <div id="comment_<%= comment.id.to_s %>_top_div" class="comment_div">
    <span id="comment_<%= comment.id.to_s %>_commontator_span" class="comment_commontator">
      <%= link.blank? ? name : link_to(name, link) %>
    </span>
    <span id="comment_<%= comment.id.to_s %>_actions_span" class="comment_actions">
      <%= render :partial => 'commontator/comments/actions',
                 :locals => { :comment => comment,
                              :user => user } %>
    </span>
  </div>
  <div id="comment_<%= comment.id.to_s %>_middle_div" class="comment_div">
    <span id="comment_<%= comment.id.to_s %>_avatar_span" class="comment_avatar">
      <% if user.image.thumby.url.present?%>
      <%= image_tag(user.image.thumby.url, class: 'img-circle', style: 'margin-right:-5px; margin-left:3px; margin-top:6px' ) %>
      <% else %>
        <%=  avatar %>
      <% end %>
    </span>
    <span id="comment_<%= comment.id.to_s %>_votes_span" class="comment_votes">
      <%= render :partial => 'commontator/comments/votes',
                 :locals => { :comment => comment,
                              :user => user } %>
    </span>
    <div id="comment_<%= comment.id.to_s %>_body_div" class="comment_body">
      <%= render :partial => 'commontator/comments/body',
                 :locals => { :comment => comment } %>
    </div>
  </div>
  <div id="comment_<%= comment.id.to_s %>_bottom_div" class="comment_div">
    <span id="comment_<%= comment.id.to_s %>_created_timestamp_span" class="comment_timestamp">
      <%= comment.created_timestamp %>
    </span>
    <br/>
    <span id="comment_<%= comment.id.to_s %>_updated_timestamp_span" class="comment_timestamp">
    <% if comment.is_modified? %>
      <%= comment.updated_timestamp %>
    <% end %>
    </span>
  </div>
</div>

app/views/commontator/comments/_votes.html.erb
<% # Clients of this partial must provide the following variables:
   # comment
   # user
%>

<% if comment.can_be_voted_on? %>
  <% can_vote = comment.can_be_voted_on_by?(user) %>
  <% vote = comment.get_vote_by(user) %>
  <% comment_voting = comment.thread.config.comment_voting.to_sym %>

  <% if comment_voting == :ld || comment_voting == :l %>
  <% vtype = (comment_voting == :ld) ? 'upvote' : 'like' %>
  <span id="comment_<%= comment.id %>_<%= vtype %>_span"
        class="comment_<%= vtype %>">
    <% if can_vote && (vote.blank? || !vote.vote_flag) %>
      <%= form_tag commontator.upvote_comment_path(comment),
            :method => :put,
            :remote => true do %>
        <%= image_submit_tag "commontator/upvote.png",
              :onmouseover => "this.src='#{image_path("commontator/upvote_hover.png")}'",
              :onmouseout => "this.src='#{image_path("commontator/upvote.png")}'" %>
      <% end %>
    <% elsif can_vote %>
      <%= form_tag commontator.unvote_comment_path(comment),
            :method => :put,
            :remote => true do %>
        <%= image_submit_tag "commontator/upvote_active.png",
              :onmouseover => "this.src='#{image_path("commontator/upvote.png")}'",
              :onmouseout => "this.src='#{image_path("commontator/upvote_active.png")}'"
        %>
      <% end %>
    <% else %>
      <%= image_tag "commontator/upvote_disabled.png" %>
    <% end %>
  </span>
  <% end %>

  <span id="comment_<%= comment.id %>_vote_count_span" class="comment_vote_count">
    <% config = comment.thread.config %>
    <%= config.vote_count_proc.call(comment.thread,
          comment.get_upvotes.size, comment.get_downvotes.size) %>
  </span>

  <% if comment_voting == :ld %>
  <span id="comment_<%= comment.id %>_downvote_span" class="comment_downvote">
    <% if can_vote && (vote.blank? || vote.vote_flag) %>
      <%= form_tag commontator.downvote_comment_path(comment),
            :method => :put,
            :remote => true do %>
        <%= image_submit_tag "commontator/downvote.png",
              :onmouseover => "this.src='#{image_path("commontator/downvote_hover.png")}'",
              :onmouseout => "this.src='#{image_path("commontator/downvote.png")}'" %>
      <% end %>
    <% elsif can_vote %>
      <%= form_tag commontator.unvote_comment_path(comment),
            :method => :put,
            :remote => true do %>
        <%= image_submit_tag "commontator/downvote_active.png",
              :onmouseover => "this.src='#{image_path("commontator/downvote.png")}'",
              :onmouseout => "this.src='#{image_path("commontator/downvote_active.png")}'"
        %>
      <% end %>
    <% else %>
      <%= image_tag "commontator/downvote_disabled.png" %>
    <% end %>
  </span>
  <% end %>
<% end %>

app/views/commontator/comments/cancel.js.erb
<% unless @comment.try(:id).blank? %>
  <% @comment.reload %>
  $("#comment_<%= @comment.id.to_s %>_body_div").html("<%= escape_javascript(
    render :partial => 'body', :locals => { :comment => @comment }) %>");
<% end %>

<% unless @new_comment.nil? %>
  $("#thread_<%= @thread.id %>_new_comment_form_div").html("<%= escape_javascript(
    render :partial => 'form',
           :locals => { :comment => @new_comment,
                        :thread => @thread,
                        :per_page => @per_page }) %>");
<% else %>
  $("#thread_<%= @thread.id %>_new_comment_form_div").hide();

  $("#thread_<%= @thread.id %>_new_comment_link_div").fadeIn();
<% end %>

<%= javascript_proc %>

app/views/commontator/comments/create.js.erb
<%= render :partial => 'commontator/threads/show',
           :locals => { :thread => @thread,
                        :user => @user,
                        :page => @thread.new_comment_page(@per_page),
                        :per_page => @per_page } %>

<% unless @new_comment.nil? %>
  $("#thread_<%= @thread.id %>_new_comment_form_div").html("<%= escape_javascript(
    render :partial => 'form',
           :locals => { :comment => @new_comment,
                        :thread => @thread,
                        :per_page => @per_page }) %>");
<% else %>
  $("#thread_<%= @thread.id %>_new_comment_form_div").hide();

  $("#thread_<%= @thread.id %>_new_comment_link_div").fadeIn();
<% end %>

$("#comment_<%= @comment.id.to_s %>_div").hide().fadeIn()[0].scrollIntoView();

<%= javascript_proc %>

app/views/commontator/comments/delete.js.erb
$("#comment_<%= @comment.id.to_s %>_body_div").html("<%= escape_javascript(render :partial => 'body', :locals => { :comment => @comment }) %>");

$("#comment_<%= @comment.id.to_s %>_updated_timestamp_span").html("<%= escape_javascript( @comment.updated_timestamp) %>");

$("#comment_<%= @comment.id.to_s %>_actions_span").html("<%= escape_javascript(render :partial => 'actions', :locals => { :comment => @comment, :user => @user }) %>");

$("#comment_<%= @comment.id %>_votes_span").html("<%= escape_javascript( render :partial => 'votes',:locals => { :comment => @comment, :user => @user }) %>");

<%= javascript_proc %>

app/views/commontator/comments/edit.js.erb
$("#comment_<%= @comment.id.to_s %>_body_div").html("<%= escape_javascript(
  render :partial => 'form',
         :locals => { :comment => @comment }) %>");
         
<%= javascript_proc %>

app/views/commontator/comments/new.js.erb
$("#thread_<%= @thread.id %>_new_comment_form_div").html("<%= escape_javascript(
  render :partial => 'form',
         :locals => { :comment => @comment,
                      :thread => @thread,
                      :per_page => @per_page }) %>");

$("#thread_<%= @thread.id %>_new_comment_form_div").fadeIn()[0].scrollIntoView();

$("#thread_<%= @thread.id %>_new_comment_link_div").hide();

<%= javascript_proc %>

app/views/commontator/comments/update.js.erb
$("#comment_<%= @comment.id.to_s %>_body_div").html("<%= escape_javascript(
  render :partial => 'body', :locals => { :comment => @comment }) %>");

$("#comment_<%= @comment.id.to_s %>_updated_timestamp_span").html("<%= escape_javascript(
  @comment.updated_timestamp) %>");

<%= javascript_proc %>

app/views/commontator/comments/vote.js.erb
$("#comment_<%= @comment.id %>_votes_span").html("<%= escape_javascript(
  render :partial => 'votes',
         :locals => { :comment => @comment,
                      :user => @user }) %>");

<%= javascript_proc %>

app/views/commontator/subscriptions/_link.html.erb
<% # Clients of this partial must supply the following variables:
   # thread
   # user
%>

<% is_subscribed = !!thread.subscription_for(user) %>
<% sub_string = is_subscribed ? "unsubscribe" : "subscribe" %>
<%= link_to t("commontator.subscription.actions.#{sub_string}"),
            commontator.polymorphic_path([sub_string, thread]),
            :confirm => (is_subscribed ? t('commontator.subscription.actions.confirm_unsubscribe') : \
                          nil),
            :method => :put,
            :id => "thread_#{thread.id.to_s}_#{sub_string}_link",
            :class => "thread_#{sub_string}_link",
            :remote => true %>

app/views/commontator/subscriptions/subscribe.js.erb
$("#thread_<%= @thread.id.to_s %>_subscription_span").html("<%= escape_javascript(
  render :partial => 'link',
         :locals => { :thread => @thread,
                      :user => @user }) %>");

<%= javascript_proc %>

app/views/partials/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <p><i class="fa fa-copyright" aria-hidden="true"></i> 2017 Campus, All rights reserved.</p>
  </div>
</footer>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">

    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand logo-estilo" href="/">
                <i class="fa fa-university" aria-hidden="true"></i>CAMPUS</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <% if user_signed_in? && current_page?(channels_path)%>
            <form class="navbar-form navbar-left" role="search">
                <div class="input-group">
                    <%= form_tag(channels_path, :method => "get", id: "search-form") do %>
                    <%= text_field_tag :search, params[:search], placeholder: "Buscar canales...", class: 'form-control barra-busqueda' %>
                    <span class="input-group-btn">
                        <%= submit_tag "Buscar", :name => nil, class: 'btn btn-success' %>
                    </span>
                    <% end %>
                </div>

            </form>

            <% end %>

            <ul class="nav navbar-nav navbar-right">

                <% if user_signed_in? %>
                <li>

                    <%= link_to perfil_index_path do %>
                    <% if current_user.image.thumby.url.present?%>
                    <%=  image_tag(current_user.image.thumby.url, class: 'img-circle', style: 'margin-right:8px; margin-top:-6px;' ) %><% end %>
                    <strong><%= current_user.nombre %>
                    </strong>
                    <% end %>

                </li>
                <li>
                    <%= link_to fa_icon("Cerrarsesion", text: "Cerrar Sesion", class: "fa-sign-out"), destroy_user_session_path, :method => :delete %>
                </li>
            <% else %>
                <li>
                    <% unless current_page?(about_index_path) %>
                    <%= link_to fa_icon("Sobrenosotros", text: "Sobre Nosotros", class: "fa-info-circle"), about_index_path %>
                    <% end %>
                </li>
                <% end %>

                <%if user_signed_in? %>
                <li class="<%= 'active' if params[:controller] == 'welcome' %>, visible-xs">
                    <%= link_to welcome_index_path do %>
                    <i class="fa fa-home" aria-hidden="true"></i>
                    <span style="margin-left:10px;">Timeline
                    </span>
                    <% end %>
                </li>
                <li class="<%= 'active' if params[:controller] == 'channels'%>, visible-xs ">
                    <%= link_to channels_path do %>
                    <i class="fa fa-th-large" aria-hidden="true"></i>
                    <span style="margin-left:10px;">Canales</span>
                    <% end %>
                </li>
                <% if request.path == "/chanel/index" %>
                <li class="<%= 'active' if params[:controller] == 'chanel' %>, visible-xs">
                    <%= link_to chanel_index_path do %>
                    <i class="fa fa-th-large " style="font-size: 15px; margin-left: 30px;" aria-hidden="true"></i>
                    <span style="margin-left:10px; font-size: 15px;">Público</span>
                    <% end %>
                </li>
                <% end %>

                <% if current_user.email == 'pm@gmail.com' %>
                <li class="<%= 'active' if params[:controller] == 'areas' %>, visible-xs">
                    <%= link_to areas_path do %>
                    <i class="fa fa-book" aria-hidden="true"></i>
                    <span style="margin-left:10px;">Áreas de conocimiento</span>
                    <% end %>
                </li>
                <% end %>
                <% end %>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/partials/_paginate.html.erb
<div id="endless-scroll" class="well text-center hidden">
  <%= image_tag 'ajax-loader.gif' %>
  <%= will_paginate resources %>
</div>

app/views/partials/_sidebar.html.erb
<div class="col-xs-1 col-md-2 collapse in hidden-xs">
    <div class="container-fluid">
        <div class="box">
            <div class="text-left">
                <ul class="nav nav-sidebar">
                    <li class="<%= 'active' if params[:controller] == 'welcome' %>">
                        <%= link_to welcome_index_path do %>
                        <i class="fa fa-home" aria-hidden="true"></i>
                        <span style="margin-left:10px;">Timeline
                        </span>
                        <% end %>
                    </li>
                    <li class="<%= 'active' if params[:controller] == 'perfil' %>">
                        <%= link_to perfil_index_path do %>
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <span style="margin-left:10px;">Perfil
                        </span>
                        <% end %>
                    </li>
                    <li class="<%= 'active' if params[:controller] == 'channels' %>">
                        <%= link_to channels_path do %>
                        <i class="fa fa-th-large" aria-hidden="true"></i>
                        <span style="margin-left:10px;">Canales</span>
                        <% end %>
                    </li>                    
                    <% if current_user.email == 'ani@gmail.com' %>
                    <li class="<%= 'active' if params[:controller] == 'areas' %>">
                        <%= link_to areas_path do %>
                        <i class="fa fa-book" aria-hidden="true"></i>
                        <span style="margin-left:10px;">Areas</span>
                        <% end %>
                    </li>
                    <% end %>
                </ul>
                <hr class="linea-hr2">
                <ul class="nav nav-sidebar">
                    <li>
                        <%= link_to about_index_path do %>
                        <i class="fa fa-building-o" aria-hidden="true"></i>
                        <span style="margin-left:10px;">Sobre Nosotros</span>
                        <% end %>
                    </li>

                </ul>
            </div>
        </div>
    </div>
</div>