config/routes.rb
Rails.application.routes.draw do


  resources :friendships
  resources :profiles
  get 'follows/create'
  get 'follows/destroy'
  get 'user/create'
  get 'chanel/index'
  get 'perfil/index'
  get 'about/index'


  resources :channels
  resources :areas
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :user do
    member do
      get :followers
    end
  end
  get 'welcome/index'
  get 'users/:id' => 'users#show'
 resources :posts do
      member do
      put "like", to: "posts#upvote"
      put "unlike", to: "posts#downvote"
    end
  end
  
mount Commontator::Engine => '/commontator'

devise_scope :user do
  authenticated :user do
    root 'welcome#index', as: :authenticated_root
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

match :follow, to: 'follows#create', as: :follow, via: :post
match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
	#has_and_belongs_to_many :users  #Crea una entidad intermedia en la base de datos llamada AreaUser
	#has_and_belongs_to_many :channels #Crea una entidad intermedia en la base de datos llamada AreaChannel
  has_many :knowledges
  has_many :users, through: :knowledges
  has_many :timelines
  has_many :channels, through: :timelines
end

app/models/channel.rb
class Channel < ApplicationRecord
  #has_and_belongs_to_many :areas #Crea una entidad intermedia en la base de datos llamada AreaChannel
  belongs_to :user
  has_many :posts
  has_many :timelines
  has_many :areas, through: :timelines
  mount_uploader :image, ImageUploader

  def self.search(search)
    where("nombre LIKE ?", "%#{search}%")
    where("descripcion LIKE ?", "%#{search}%")
  end
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

  validates_presence_of :follower
  validates_presence_of :followable
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/knowledge.rb
class Knowledge < ApplicationRecord
  belongs_to :area
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  acts_as_commontable
  has_many :comments
  belongs_to :user
  belongs_to :channel

  validates :contenido, :presence => true, :if => :imagenvacia?

  def imagenvacia?
    image.nil?
  end
  mount_uploader :image, ImageUploader

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  belongs_to :area
  belongs_to :channel
end

app/models/user.rb
require "httparty"
require "json"

class User < ApplicationRecord
  has_many :comments
  has_many :posts, dependent: :destroy
  has_many :channels
  has_many :knowledges
  has_one :profile
  has_many :areas, through: :knowledges
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :anti_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :anti_friends, :through => :anti_friendships, :source => :user
  acts_as_commontator
  acts_as_followable
  acts_as_follower
  validates :cedula, :presence => true
  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include HTTParty
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   def self.validacion

      @json = get("http://localhost:4040/graduates.json")
      @json = @json.to_json
      @parsed_json = ActiveSupport::JSON.decode(@json)
      @no = @parsed_json

      return @no

    end

    def self.search(search)
      where("nombre LIKE ?", "%#{search}%")
      where("apellido LIKE ?", "%#{search}%")
    end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
      if @friendship.save
        flash[:notice] = "Has seguido a un usuario."
        redirect_to :back
      else
        flash[:error] = "No fue posible seguir a el usuario."
        redirect_to :back
      end
  end


  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] = "Has seguido a un usuario."
    redirect_to :back

  end


end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/chanel_helper.rb
module ChanelHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/perfil_helper.rb
module PerfilHelper
  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/user_helper.rb
module UserHelper
  def is_current_user?(user)
    user == current_user
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friendships/_form.html.erb
<%= form_for(friendship) do |f| %>
  <% if friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :friend_id %>
    <%= f.text_field :friend_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friendships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.user %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>