config/routes.rb
Rails.application.routes.draw do


  resources :friendships
  resources :profiles
  get 'follows/create'
  get 'follows/destroy'
  get 'user/create'
  get 'chanel/index'
  get 'perfil/index'
  get 'about/index'


  resources :channels
  resources :areas
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :user do
    member do
      get :followers
    end
  end
  get 'welcome/index'
  get 'users/:id' => 'users#show'
 resources :posts do
      member do
      put "like", to: "posts#upvote"
      put "unlike", to: "posts#downvote"
    end
  end
  
mount Commontator::Engine => '/commontator'

devise_scope :user do
  authenticated :user do
    root 'welcome#index', as: :authenticated_root
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

match :follow, to: 'follows#create', as: :follow, via: :post
match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
	#has_and_belongs_to_many :users  #Crea una entidad intermedia en la base de datos llamada AreaUser
	#has_and_belongs_to_many :channels #Crea una entidad intermedia en la base de datos llamada AreaChannel
  has_many :knowledges
  has_many :users, through: :knowledges
  has_many :timelines
  has_many :channels, through: :timelines
end

app/models/channel.rb
class Channel < ApplicationRecord
  #has_and_belongs_to_many :areas #Crea una entidad intermedia en la base de datos llamada AreaChannel
  belongs_to :user
  has_many :posts
  has_many :timelines
  has_many :areas, through: :timelines
  mount_uploader :image, ImageUploader

  def self.search(search)
    where("nombre LIKE ?", "%#{search}%")
    where("descripcion LIKE ?", "%#{search}%")
  end
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

  validates_presence_of :follower
  validates_presence_of :followable
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/knowledge.rb
class Knowledge < ApplicationRecord
  belongs_to :area
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  acts_as_commontable
  has_many :comments
  belongs_to :user
  belongs_to :channel

  validates :contenido, :presence => true, :if => :imagenvacia?

  def imagenvacia?
    image.nil?
  end
  mount_uploader :image, ImageUploader

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  belongs_to :area
  belongs_to :channel
end

app/models/user.rb
require "httparty"
require "json"

class User < ApplicationRecord
  has_many :comments
  has_many :posts, dependent: :destroy
  has_many :channels
  has_many :knowledges
  has_one :profile
  has_many :areas, through: :knowledges
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :anti_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :anti_friends, :through => :anti_friendships, :source => :user
  acts_as_commontator
  acts_as_followable
  acts_as_follower
  validates :cedula, :presence => true
  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include HTTParty
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   def self.validacion

      @json = get("http://localhost:4040/graduates.json")
      @json = @json.to_json
      @parsed_json = ActiveSupport::JSON.decode(@json)
      @no = @parsed_json

      return @no

    end

    def self.search(search)
      where("nombre LIKE ?", "%#{search}%")
      where("apellido LIKE ?", "%#{search}%")
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def upvote
    @post.upvote_from current_user
    redirect_to :back
  end

  def downvote
     @post.downvote_from current_user
     redirect_to :back
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save

        format.html { redirect_to :back, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        format.js
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end



  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to @post, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:contenido, :tipo_post, :me_gusta, :user_id, :channel_id, :image)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/chanel_helper.rb
module ChanelHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/perfil_helper.rb
module PerfilHelper
  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/user_helper.rb
module UserHelper
  def is_current_user?(user)
    user == current_user
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
<% if post.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(post.errors.count, "error") %>
        prohibited this post from being saved:</h2>

    <ul>
        <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= f.label :contenido %>
    <%= f.text_area :contenido %>
</div>

<div class="field">
    <%= f.label :tipo_post %>
    <%= f.text_field :tipo_post %>
</div>

<div class="field">
    <%= f.label :me_gusta %>
    <%= f.number_field :me_gusta %>
</div>

<div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
</div>

<div class="field">
    <%= f.label :channel_id %>
    <%= f.text_field :channel_id %>
</div>

<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/posts/_post.html.erb
<div class="panel panel-default" id="post_<%= post.id %>">

    <div class="panel-body">
        <div class="pull-left">
            <a href="#">
                <% if current_user.image.thumby.url.present?%>
                <%=  image_tag(current_user.image.thumb.url, class: 'img-circle', style: 'margin-right:8px; margin-top:-5px;' ) %>
                <% end %>

            </a>
        </div>
        <h4><%= link_to post.user.nombre, controller: "users", action: "show", id: post.user.id %>

            <small>
                <small>
                    <a href="#" style="text-decoration:none; color:grey;">
                        <i>
                            <i class="fa fa-clock-o" aria-hidden="true"></i>
                            <%= time_ago_in_words(post.created_at) %></i>
                    </a>
                </small>
            </small>
        </h4>
        <span>
            <div class="navbar-right">
                <% if current_user.id == post.user.id %>
                <div class="dropdown">
                    <button class="btn btn-link btn-xs dropdown-toggle" type="button" id="dd1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <i class="fa fa-angle-down" aria-hidden="true"></i>

                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dd1" style="float: right;">
                        <li type="button" data-toggle="modal" data-target="#myupdatepost_<%= post.id%>">
                            <i class="fa fa-pencil" style="margin-left:25px"></i>
                            <span style="margin-left:5px">Editar</span>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li>
                            <%= link_to post, method: :delete, remote: true, data: { confirm: '¿Estás seguro que deseas eliminar esta publicación?' } do %>
                            <%= fa_icon "trash", text: "Eliminar" %>
                            <% end %>
                        </li>
                    </ul>
                </div>
                <% end %>
            </div>
        </span>
        <hr>
        <div class="post-content">

            <% if post.image.present? %>
            <div class="attachment">
                <center><%= image_tag post.image.post_img.url %></center>
            </div>
            <% end %>
            <br>
            <p>
                <%= post.contenido %></p>

        </div>
        <hr>
        <div>
            <div class="pull-right btn-group-xs">

                <%= link_to like_post_path(post.id), method: :put, remote: true, class: "btn btn-default" do %>
                <span class="glyphicon glyphicon-heart"></span>
                <%= post.get_upvotes.size %>
                <% end %>

                <span class="pull-right" style="margin-left: 8px;">
                    <%= social_share_button_tag(@post.id,'data-twitter-title' => 'Chequea mi publicación en Campus:') %>
                </span>
            </div>

            <br>
        </div>
        <hr>
        <div class="media">
            <div class="pull-left">

                <a href="#">
                    <% if current_user.image.thumby.url.present?%>
                    <%=  image_tag(current_user.image.thumby.url, class: 'img-circle', style: 'margin-right:-5px; margin-left:3px; margin-top:6px' ) %>
                    <% end %>
                </a>
            </div>

            <div class="media-body">
              

            </div>
        </div>
    </div>

</div>

<!--- MODAL -->

<!-- Modal -->
<%= form_for(post, :method => :put, remote: true) do |f| %>
<div class="modal fade" id="myupdatepost_<%= post.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Editar publicación</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <%= f.text_area :contenido, class: 'form-control' %>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="myupdatebutton_<%= post.id %>" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
                <%= submit_tag "Guardar Cambios", class: "btn btn-success" %>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/posts/create.js.erb
$(".post_content").val('');
$("#container_posts").prepend('<%= j render @post %>');
$("#post_<%= @post.id %>").hide().fadeIn(1000);

app/views/posts/destroy.js.erb
$("#post_<%= @post.id %>").fadeOut(500, function(){
    $(this).remove();
});

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
    <thead>
        <tr>
            <th>Contenido</th>
            <th>Tipo post</th>
            <th>Me gusta</th>
            <th>User</th>
            <th>Channel</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @posts.each do |post| %>
        <tr>
            <td><%= post.contenido %></td>
            <td><%= post.tipo_post %></td>
            <td><%= post.me_gusta %></td>
            <td><%= post.user %></td>
            <td><%= post.channel %></td>
            <td><%= link_to 'Show', post %></td>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contenido:</strong>
  <%= @post.contenido %>
</p>

<p>
  <strong>Tipo post:</strong>
  <%= @post.tipo_post %>
</p>

<p>
  <strong>Me gusta:</strong>
  <%= @post.me_gusta %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @post.channel %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/update.js.erb
$("#myupdatepost_<%= @post.id %>").modal('hide');
$("#post_<%= @post.id %>").fadeOut(500, function(){

    $(this).remove();
    $("#container_posts").prepend('<%= j render @post %>');
});